---
# Inventaire des edges Tailscale
# ansible_host : nom MagicDNS Tailscale OU IP 100.x.x.x de la machine
# Pour trouver les IPs/noms : tailscale status

all:
  vars:
    ansible_user: ubuntu
    deploy_path: /data/app/deploy-ppc

  children:
    edges:
      hosts:
        edge-site-01:
          ansible_host: edge-site-01   # remplacer par le nom MagicDNS ou l'IP Tailscale
        edge-site-02:
          ansible_host: edge-site-02   # remplacer par le nom MagicDNS ou l'IP Tailscale
