version: "3"

services:
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail.yml
      - ./positions:/positions
      - /data/ppc/logs:/var/log/ppc:ro
    environment:
      - SITE_NAME=${site_name}
    command: -config.file=/etc/promtail/promtail.yml -config.expand-env=true
    dns:
      - 100.100.100.100